# Generated by Django 4.2.5 on 2023-09-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Excellent'), (2, 'Good'), (3, 'Not Bad'), (4, 'Bad'), (5, 'Worst')]),
        ),
    ]
